#!/usr/bin/env bash
# PreToolUse (Edit|Write|NotebookEdit|Bash): enforce what AGENTS.md can only ask for.
#   deny  key material written by an edit tool anywhere (its content would
#         come from the model), or by the shell inside the repo
#   deny  a shell command that prints key material (cat, grep, git diff, …),
#         which would put the secret into the conversation
#   deny  the brand masters (Petr authors them; they are only ever read)
#   deny  SOPS files, generated files and lockfiles in the repo
#   ask   project.pbxproj (Xcode's own format)
# Piping a secret from 1Password into a file outside the repo for a command
# to consume (`op read … > "$tmp/key.jks"`) stays allowed: nothing is printed.
# tool_paths.py resolves which files a call writes or reads, including shell
# redirections, sed -i, tee, cp/mv, heredocs, wrappers (`sudo -u x cat …`) and
# recursive searches (`grep -r`, `rg`, `find -exec cat`); its docstring has the
# limits. If it fails, the call is denied: a guard that cannot read a command
# must not wave it through.
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:?}"
input="$(cat)"

deny_json() {
  python3 -c 'import json, sys
print(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse",
      "permissionDecision": sys.argv[1], "permissionDecisionReason": sys.argv[2]}}))' "$@"
}

if ! paths="$(printf '%s' "$input" | python3 "$(dirname "$0")/tool_paths.py" 2>/dev/null)"; then
  deny_json deny "guard-edits.sh could not parse this call (tool_paths.py failed); rephrase it."
  exit 0
fi

verdict="" reason=""
# The most restrictive answer wins: deny > ask.
decide() {
  [[ "$verdict" == deny || ("$verdict" == ask && "$1" == ask) ]] && return
  verdict="$1" reason="$2"
}

key_material() {
  case "$1" in
    *.example | *.example.* | *.sample | *.template | *.dist) return 1 ;; # committed templates
    .env | .env.* | *.env | *.p8 | *.p12 | *.pem | *.key | *.jks | *.keystore | key.properties | \
      service-account*.json | google-services.json | GoogleService-Info.plist | *.mobileprovision) return 0 ;;
  esac
  return 1
}

while IFS=$'\t' read -r kind path; do
  [[ -n "$path" ]] || continue
  rel="${path#"$root/"}"
  base="${rel##*/}"
  inside=false
  [[ "$path" == "$root/"* ]] && inside=true
  if key_material "$base"; then
    case "$kind" in
      E) decide deny "$rel holds key material. Secrets live in 1Password and SOPS and never pass through the model (AGENTS.md)." ;;
      W) $inside && decide deny "$rel holds key material. Materialise it with \`just secrets-decrypt\` or the release recipe (docs/release.md), not by hand." ;;
      R) decide deny "$rel holds key material; printing it would put the secret into the conversation (AGENTS.md). Let the command that needs it read it (\`source\`, \`--env-file\`, \`op read\` piped into it). A recursive search reaches it too: use \`rg\` or \`git grep\` (they skip gitignored and hidden files) or name the paths you mean." ;;
    esac
    continue
  fi
  # Everything below guards the repo's own files against being written.
  if [[ "$kind" == R ]] || ! $inside; then continue; fi
  case "$base" in
    pubspec.lock | Podfile.lock | uv.lock | package-lock.json)
      decide deny "$rel is a lockfile; change the manifest and let the package manager rewrite it (flutter pub, pod install, uv, npm)." ;;
    *.sops)
      decide deny "$rel is SOPS-encrypted; change it with scripts/secrets-edit.sh." ;;
    *.g.dart)
      decide deny "$rel is generated by drift; change the tables and run \`dart run build_runner build\` in apps/mobile." ;;
    project.pbxproj)
      decide ask "Hand edits corrupt project.pbxproj easily; prefer Xcode or an xcodeproj script." ;;
  esac
  # Leading slash so top-level directories match too.
  case "/$rel" in
    /apps/mobile/build/app/outputs/*) ;; # release artefacts are renamed there (docs/release.md, step 4)
    /assets-source/brand/*.png)
      decide deny "$rel is a brand master Petr authors; never generate or change it. Ask him for a new master (assets-source/brand/README.md)." ;;
    */ios/Flutter/Generated.xcconfig | */ios/Flutter/flutter_export_environment.sh | */GeneratedPluginRegistrant.* | \
      */.dart_tool/* | */build/* | */node_modules/* | /apps/api/web/dist/* | */api_client/generated/*)
      decide deny "$rel is generated by Flutter, npm or a build; change its source instead." ;;
  esac
done <<<"$paths"

[[ -n "$verdict" ]] || exit 0
deny_json "$verdict" "$reason"
